export const campaignTypes = {
    EC_ADD_INIT: 'EC_ADD_INIT',
    EC_ADD_START: 'EC_ADD_START',
    EC_ADD_SUCCESS: 'EC_ADD_SUCCESS',
    EC_ADD_FAIL: 'EC_ADD_FAIL',
    EC_CHECK_START:'EC_CHECK_START',
    EC_CHECK_INIT:'EC_CHECK_INIT',
    EC_CHECK_SUCCESS:'EC_CHECK_SUCCESS',
    EC_CHECK_FAIL:'EC_CHECK_FAIL',
}